version: 0.2
phases:
  pre_build:
    commands:
      - echo "Pro build phase - Exemplo baixar dependencias se fosse necessario"
  build:
    commands:
      - echo "Running tests"
      - mvn clean test
      - echo "Building"
      - mvn clean compile package
  post_build:
    commands:
      - echo "Movendo os arquivos que serao feitos upload"
      - mv target/*.war ./ROOT.war
artifacts:
  files:
    - ROOT.war