version: "3"
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    expose:
      - 3306
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=antenas