server:
  port: 8081

build.name: @project.name@
build.version: @project.version@

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_DATABASE:abc_tech}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}

