server:
  port: 8081

build.name: @project.name@
build.version: @project.version@

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
#  jpa:
#    hibernate:
#      ddl-auto: create